name: sample workflow

on:
  workflow_dispatch:

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      - name: say hello
        run: echo "Hello World"

      - name: checkout source code
        uses: actions/checkout@v2
      
      - name: run command
        run: |
          pwd
          ls
